---
- name: Nexus | Install Dependencies
  ansible.builtin.include_tasks: pre.yml

- name: Nexus | Install Nexus
  ansible.builtin.include_tasks: install.yml

- name: Nexus | Config Nexus
  ansible.builtin.include_tasks: config.yml

- name: Nexus | Config realms
  ansible.builtin.include_tasks: realms.yml

- name: Nexus | Config docker proxy repositories
  ansible.builtin.include_tasks: repositories/docker_proxy.yml
  with_items: "{{ nexus_docker_proxy_repositories }}"

- name: Nexus | Config docker groups
  ansible.builtin.include_tasks: repositories/docker_group.yml
  with_items: "{{ nexus_docker_groups }}"

- name: Nexus | Config YUM proxy repositories
  ansible.builtin.include_tasks: repositories/yum_proxy.yml
  with_items: "{{ nexus_yum_proxy_repositories }}"

- name: Nexus | Config pypi proxy repositories
  ansible.builtin.include_tasks: repositories/pypi_proxy.yml
  with_items: "{{ nexus_pypi_proxy_repositories }}"

- name: Nexus | Config proxy repositories
  ansible.builtin.include_tasks: repositories/raw_proxy.yml
  with_items: "{{ nexus_raw_proxy_repositories }}"
