---
- name: Nexus | Install Dependencies
  ansible.builtin.include_tasks: pre.yml

- name: Nexus | Install Nexus
  ansible.builtin.include_tasks: install.yml

- name: Nexus | Config Nexus
  ansible.builtin.include_tasks: config.yml

- name: Nexus | Config YUM proxy repo
  ansible.builtin.include_tasks: repos/yum_proxy.yml
  with_items: "{{ nexus_yum_proxy_repos }}"

- name: Nexus | Config realms
  ansible.builtin.include_tasks: realms.yml

- name: Nexus | Config docker proxy repos
  ansible.builtin.include_tasks: repos/docker_proxy.yml
  with_items: "{{ nexus_docker_proxy_repos }}"

- name: Nexus | Config docker groups
  ansible.builtin.include_tasks: repos/docker_group.yml
  with_items: "{{ nexus_docker_groups }}"

- name: Nexus | Config pypi proxy repos
  ansible.builtin.include_tasks: repos/pypi_proxy.yml
  with_items: "{{ nexus_pypi_proxys }}"
