---
- name: Nexus | Nexus application-port
  community.general.ini_file:
    path: /opt/sonatype-work/nexus3/etc/nexus.properties
    option: application-port
    value: "{{ nexus_bind_port }}"
    state: present
    no_extra_spaces: true
    owner: nexus
    group: nexus
  when: not stat_result.stat.exists
