---
driver:
  name: docker

platforms:
- name: nexus.molecule
  image: docker.io/library/oraclelinux:9
  pre_build_image: true
  privileged: true
  cgroupns_mode: host
  tmpfs:
  - /tmp
  - /run
  capabilities:
  - SYS_ADMIN
  command: "/usr/lib/systemd/systemd"
  groups:
  - nexus
  networks:
  - name: molecule
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      nexus:
        nexus_java_pkg: java-17-openjdk
        nexus_version: 3.76.1-01
        nexus_major_version: "{{ nexus_version.split('.')[0] }}"
        nexus_admin_password: "password"
        nexus_bind_port: 8081
        nexus_api_url: "http://localhost:{{nexus_bind_port}}/service/rest"
        nexus_default_properties:
        - { option: application-port,              value: "{{ nexus_bind_port }}" }
        - { option: nexus.skipDefaultRepositories, value: "true" }
        nexus_properties:
        - { option: application-port, value: "{{ nexus_bind_port }}" }
        - { option: application-host, value: "0.0.0.0" }
        nexus_yum_proxy_repositories:
        - name: hashicorp-rhel-proxy
          url: https://rpm.releases.hashicorp.com/RHEL
        nexus_docker_proxy_repositories:
        - name: dockerhub-proxy
          url: https://registry-1.docker.io 
          index_type: "HUB"
        nexus_docker_groups:
        - name: docker-proxy-all
          members: "{{ nexus_docker_proxy_repositories | map(attribute='name') | list | unique }}"
          http_port: 5000
        nexus_pypi_proxy_repositories:
        - name: pypi-proxy
          url: https://pypi.org
        nexus_raw_proxy_repositories:
        - name: flatcar-stable-proxy
          url: https://stable.release.flatcar-linux.net

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
