---
driver:
  name: docker

platforms:
- name: nexus.molecule
  image: docker.io/library/oraclelinux:9
  pre_build_image: true
  privileged: true
  cgroupns_mode: host
  tmpfs:
  - /tmp
  - /run
  capabilities:
  - SYS_ADMIN
  command: "/usr/lib/systemd/systemd"
  groups:
  - nexus
  networks:
  - name: molecule
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      nexus:
        nexus_java_pkg: java-17-openjdk
        nexus_version: 3.76.1-01
        nexus_major_version: "{{ nexus_version.split('.')[0] }}"
        nexus_admin_password: "password"
        nexus_bind_port: 8081
        nexus_api_url: "http://localhost:{{nexus_bind_port}}/service/rest"
        nexus_yum_proxy_repos:
        - name: "hashicorp-rhel"
          url: "https://rpm.releases.hashicorp.com/RHEL"
        nexus_docker_proxy_repos:
        - name: "dockerhub"
          url: "https://registry-1.docker.io" 
          index_type: "HUB"
        nexus_docker_groups:
        - name: "docker-proxy-all"
          members: "{{ nexus_docker_proxy_repos | map(attribute='name') | list | unique }}"
          http_port: 5000

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
