---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:

  - name: Verify | Install skopeo
    ansible.builtin.yum:
      name: skopeo

  - name: Verify | Check Nexus api 
    ansible.builtin.uri:
      url: "{{ nexus_api_url }}/v1/status"
      user: admin
      password: "{{ nexus_admin_password }}"
      method: GET
      force_basic_auth: true

  - name: Verify | Check docker registry (download images)
    ansible.builtin.shell: skopeo copy --src-tls-verify=false docker://localhost:5000/{{item}} docker-archive:/tmp/{{item}}.tar
    with_items: ["ubuntu", "debian", "alpine"]

  - name: Verify | Import hashicorp repo gpg key
    ansible.builtin.rpm_key:
      state: present
      key: https://rpm.releases.hashicorp.com/gpg

  - name: Verify | Add hashicorp repo
    ansible.builtin.yum_repository:
      name: hashicorp
      description: Hashicorp Stable - $basearch
      file: hashicorp
      baseurl: http://localhost:8081/repository/hashicorp-rhel-proxy/$releasever/$basearch/stable
      gpgcakey: https://rpm.releases.hashicorp.com/gpg
      gpgcheck: yes

  - name: Verify | Install consul from hashicorp repo
    ansible.builtin.yum:
      name: consul
      enablerepo: 'hashicorp'
      disablerepo: '*'

  - name: Verify | Check hashicorp package
    ansible.builtin.shell: yum info consul | grep 'From repo' | grep hashicorp

  - name: Verify | Install python3-pip
    ansible.builtin.yum:
      name: python3-pip

  - name: Verify | Update pip3
    ansible.builtin.pip:
      name: pip
      extra_args: " -i http://localhost:8081/repository/pypi-proxy/simple --upgrade"

  - name: Verify | Install ansible over pip
    ansible.builtin.pip:
      name: ["ansible-core==2.15", "ansible"]
      extra_args: " -i http://localhost:8081/repository/pypi-proxy/simple"
      umask: "0022"

  - name: Check ansible
    ansible.builtin.command: ansible --version
    environment: 
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

  - name: Download file from raw proxy repo
    ansible.builtin.get_url:
      url: http://localhost:8081/repository/flatcar-stable-proxy/amd64-usr/current/flatcar_production_qemu_image.img.bz2
      dest: /tmp/flatcar_production_qemu_image.img.bz2
      checksum: md5:http://localhost:8081/repository/flatcar-stable-proxy/amd64-usr/current/flatcar_production_qemu_image.img.bz2.DIGESTS
      timeout: 120
