---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  
  - name: Verify | Check Nexus api 
    ansible.builtin.uri:
      url: "{{ nexus_api_url }}/v1/status"
      user: admin
      password: "{{ nexus_admin_password }}"
      method: GET
      force_basic_auth: true
